name: PR Checks

on:
  pull_request:
    branches: [trunk]

permissions:
  contents: read

concurrency:
  group: pr-checks-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
